import type { CardDef, Desk, PowerDef, Seat } from "./types.ts";

export const HEROES: Record<
  Desk,
  {
    name: string;
    blurb: string;
    powers: Record<Seat, PowerDef>;
  }
> = {
  whale: {
    name: "巨鯨",
    blurb: "水深、壓盤、一口把板位吃滿。",
    powers: {
      house: { name: "壓盤", cost: 2, text: "對所有敵方標的造成 1 點傷害。", kind: { k: "aoe", n: 1 } },
      retail: { name: "掃貨", cost: 2, text: "召喚一個 1/1 小單。", kind: { k: "summon", defId: "sprat" } },
    },
  },
  maker: {
    name: "做市商",
    blurb: "兩邊掛價，用報價牆換抽牌同清場。",
    powers: {
      house: { name: "賣價", cost: 2, text: "使一個友方標的獲得 +1/+1。", kind: { k: "buff", a: 1, h: 1 } },
      retail: { name: "買價", cost: 2, text: "召喚一個 1/2 護盤報價。", kind: { k: "summon", defId: "slip" } },
    },
  },
  growth: {
    name: "複利",
    blurb: "養大流動性，提早打出大倉。",
    powers: {
      house: { name: "加息", cost: 2, text: "流動性上限 +1，本回合也多 1 點。", kind: { k: "ramp", n: 1 } },
      retail: { name: "發芽", cost: 2, text: "召喚一個 1/2 新芽。回合結束時它 +1/+1。", kind: { k: "summon", defId: "sprout" } },
    },
  },
};

const list: CardDef[] = [
  {
    id: "meme",
    name: "迷因幣",
    ticker: "MEME",
    cost: 1,
    type: "minion",
    attack: 2,
    health: 1,
    text: "市價。上場當回合就能攻擊。",
    rarity: "common",
    seat: "any",
    desk: "neutral",
    target: "none",
    charge: true,
  },
  {
    id: "fomo",
    name: "熱搜題材",
    ticker: "HOT",
    cost: 1,
    type: "spell",
    text: "對對手造成 2 點傷害。",
    rarity: "common",
    seat: "any",
    desk: "whale",
    target: "none",
    effects: [{ k: "dmg", n: 2, to: "enemyHero" }],
  },
  {
    id: "etf",
    name: "指數基金",
    ticker: "ETF",
    cost: 2,
    type: "minion",
    attack: 2,
    health: 3,
    text: "護盤。敵方攻擊時必須先打它。",
    rarity: "common",
    seat: "any",
    desk: "neutral",
    target: "none",
    taunt: true,
  },
  {
    id: "day",
    name: "當沖客",
    ticker: "DAY",
    cost: 2,
    type: "minion",
    attack: 3,
    health: 1,
    text: "當沖。上場當回合可攻擊敵方標的，不能打對手。",
    rarity: "common",
    seat: "any",
    desk: "neutral",
    target: "none",
    rush: true,
  },
  {
    id: "beat",
    name: "財報利多",
    ticker: "BEAT",
    cost: 2,
    type: "spell",
    text: "使一個友方標的獲得 +2/+2。",
    rarity: "rare",
    seat: "any",
    desk: "whale",
    target: "friendlyMinion",
    effects: [{ k: "buff", a: 2, h: 2, to: "target" }],
  },
  {
    id: "eth",
    name: "以太坊",
    ticker: "ETH",
    cost: 3,
    type: "minion",
    attack: 3,
    health: 3,
    text: "法說：抽一張牌。",
    rarity: "rare",
    seat: "any",
    desk: "whale",
    target: "none",
    effects: [{ k: "draw", n: 1 }],
  },
  {
    id: "sq",
    name: "軋空",
    ticker: "SQZ",
    cost: 3,
    type: "spell",
    text: "對一個敵方標的造成 4 點傷害。",
    rarity: "rare",
    seat: "any",
    desk: "whale",
    target: "enemyMinion",
    effects: [{ k: "dmg", n: 4, to: "target" }],
  },
  {
    id: "lev",
    name: "槓桿多單",
    ticker: "LEV",
    cost: 3,
    type: "weapon",
    attack: 3,
    durability: 2,
    text: "裝備 3 點動能，耐久 2。每次攻擊消耗 1 耐久。",
    rarity: "rare",
    seat: "any",
    desk: "whale",
    target: "none",
  },
  {
    id: "tsla",
    name: "特斯拉",
    ticker: "TSLA",
    cost: 4,
    type: "minion",
    attack: 4,
    health: 3,
    text: "市價。上場當回合就能攻擊。",
    rarity: "rare",
    seat: "any",
    desk: "whale",
    target: "none",
    charge: true,
  },
  {
    id: "qe",
    name: "量化寬鬆",
    ticker: "QE",
    cost: 5,
    type: "spell",
    text: "你的所有標的獲得 +2/+2。",
    rarity: "epic",
    seat: "any",
    desk: "whale",
    target: "none",
    effects: [{ k: "buff", a: 2, h: 2, to: "allFriendly" }],
  },
  {
    id: "nvda",
    name: "輝達",
    ticker: "NVDA",
    cost: 5,
    type: "minion",
    attack: 4,
    health: 5,
    text: "波動。每回合可以攻擊兩次。",
    rarity: "epic",
    seat: "any",
    desk: "whale",
    target: "none",
    windfury: true,
  },
  {
    id: "btc",
    name: "比特幣",
    ticker: "BTC",
    cost: 6,
    type: "minion",
    attack: 6,
    health: 6,
    text: "法說：對對手造成 3 點傷害。",
    rarity: "epic",
    seat: "any",
    desk: "whale",
    target: "none",
    effects: [{ k: "dmg", n: 3, to: "enemyHero" }],
  },
  {
    id: "sov",
    name: "主權買盤",
    ticker: "SOV",
    cost: 7,
    type: "minion",
    attack: 6,
    health: 7,
    text: "護盤。下市：召喚一個 2/2 承銷商。",
    rarity: "epic",
    seat: "any",
    desk: "whale",
    target: "none",
    taunt: true,
    death: [{ k: "summon", defId: "uw" }],
  },
  {
    id: "uw",
    name: "承銷商",
    ticker: "UW",
    cost: 2,
    type: "minion",
    attack: 2,
    health: 2,
    text: "被主權買盤留下的部位。",
    rarity: "common",
    seat: "any",
    desk: "neutral",
    target: "none",
  },
  {
    id: "margin",
    name: "融資",
    ticker: "MRGN",
    cost: 0,
    type: "spell",
    text: "獲得 1 點流動性，僅本回合，且不超過 10。後手開局獲得。",
    rarity: "common",
    seat: "any",
    desk: "neutral",
    target: "none",
    effects: [{ k: "mana", n: 1 }],
  },
  {
    id: "vix",
    name: "恐慌指數",
    ticker: "VIX",
    cost: 1,
    type: "spell",
    text: "對一個敵方標的造成 2 點傷害。",
    rarity: "common",
    seat: "any",
    desk: "maker",
    target: "enemyMinion",
    effects: [{ k: "dmg", n: 2, to: "target" }],
  },
  {
    id: "hedge",
    name: "對沖單",
    ticker: "HDG",
    cost: 1,
    type: "minion",
    attack: 1,
    health: 3,
    text: "護盤。敵方攻擊時必須先打它。",
    rarity: "common",
    seat: "any",
    desk: "maker",
    target: "none",
    taunt: true,
  },
  {
    id: "report",
    name: "做空報告",
    ticker: "RPT",
    cost: 2,
    type: "spell",
    text: "對一個敵方標的造成 3 點傷害。",
    rarity: "common",
    seat: "any",
    desk: "maker",
    target: "enemyMinion",
    effects: [{ k: "dmg", n: 3, to: "target" }],
  },
  {
    id: "gold",
    name: "黃金",
    ticker: "GOLD",
    cost: 2,
    type: "minion",
    attack: 2,
    health: 3,
    text: "複利。造成的傷害會等量回復你的淨值。",
    rarity: "rare",
    seat: "any",
    desk: "neutral",
    target: "none",
    lifesteal: true,
  },
  {
    id: "halt",
    name: "停牌令",
    ticker: "HALT",
    cost: 2,
    type: "spell",
    text: "對一個敵方標的造成 2 點傷害，並使它停牌。",
    rarity: "rare",
    seat: "any",
    desk: "maker",
    target: "enemyMinion",
    effects: [
      { k: "dmg", n: 2, to: "target" },
      { k: "freeze" },
    ],
  },
  {
    id: "inv",
    name: "反向 ETF",
    ticker: "INV",
    cost: 3,
    type: "minion",
    attack: 3,
    health: 2,
    text: "法說：對所有敵方標的造成 1 點傷害。",
    rarity: "rare",
    seat: "any",
    desk: "maker",
    target: "none",
    effects: [{ k: "dmg", n: 1, to: "allEnemyMinions" }],
  },
  {
    id: "cut",
    name: "強制砍倉",
    ticker: "CUT",
    cost: 3,
    type: "spell",
    text: "消滅一個動能小於或等於 3 的敵方標的。",
    rarity: "rare",
    seat: "any",
    desk: "maker",
    target: "enemyMinion",
    effects: [{ k: "destroy", maxAtk: 3 }],
  },
  {
    id: "bond",
    name: "長天期債",
    ticker: "BOND",
    cost: 3,
    type: "minion",
    attack: 2,
    health: 4,
    text: "你的回合結束時，回復 2 點淨值。",
    rarity: "common",
    seat: "any",
    desk: "maker",
    target: "none",
    endTurn: [{ k: "heal", n: 2, to: "myHero" }],
  },
  {
    id: "dry",
    name: "流動性枯竭",
    ticker: "DRY",
    cost: 4,
    type: "spell",
    text: "對所有敵方標的造成 2 點傷害。",
    rarity: "rare",
    seat: "any",
    desk: "maker",
    target: "none",
    effects: [{ k: "dmg", n: 2, to: "allEnemyMinions" }],
  },
  {
    id: "bear",
    name: "熊市部位",
    ticker: "BEAR",
    cost: 4,
    type: "minion",
    attack: 3,
    health: 6,
    text: "護盤。敵方攻擊時必須先打它。",
    rarity: "common",
    seat: "any",
    desk: "maker",
    target: "none",
    taunt: true,
  },
  {
    id: "pop",
    name: "暴雷",
    ticker: "POP",
    cost: 5,
    type: "spell",
    text: "消滅一個敵方標的。",
    rarity: "epic",
    seat: "any",
    desk: "maker",
    target: "enemyMinion",
    effects: [{ k: "destroy" }],
  },
  {
    id: "sys",
    name: "系統性風險",
    ticker: "SYS",
    cost: 5,
    type: "spell",
    text: "對所有敵方標的造成 3 點傷害。",
    rarity: "epic",
    seat: "any",
    desk: "maker",
    target: "none",
    effects: [{ k: "dmg", n: 3, to: "allEnemyMinions" }],
  },
  {
    id: "fund",
    name: "避險基金",
    ticker: "FUND",
    cost: 6,
    type: "minion",
    attack: 5,
    health: 7,
    text: "護盤，止損。下市：回復 4 點淨值。",
    rarity: "epic",
    seat: "any",
    desk: "maker",
    target: "none",
    taunt: true,
    divine: true,
    death: [{ k: "heal", n: 4, to: "myHero" }],
  },
  { id: "sprat", name: "小單", ticker: "BID", cost: 1, type: "minion", attack: 1, health: 1, text: "巨鯨掃貨留下的小單。", rarity: "common", seat: "any", desk: "whale", art: "meme", target: "none" },
  { id: "slip", name: "報價", ticker: "QTE", cost: 1, type: "minion", attack: 1, health: 2, text: "護盤。做市商掛出的買價。", rarity: "common", seat: "any", desk: "maker", art: "hedge", target: "none", taunt: true },
  { id: "pier", name: "樁", ticker: "PIER", cost: 1, type: "minion", attack: 1, health: 4, text: "護盤。", rarity: "common", seat: "any", desk: "whale", art: "etf", target: "none", taunt: true },
  { id: "chunk", name: "大單", ticker: "LOT", cost: 3, type: "minion", attack: 3, health: 3, text: "一口掃進來的部位。", rarity: "common", seat: "any", desk: "whale", art: "btc", target: "none" },
  { id: "paw", name: "掃單", ticker: "PAW", cost: 1, type: "minion", attack: 2, health: 1, text: "市價。", rarity: "common", seat: "any", desk: "whale", art: "tsla", target: "none", charge: true },
  { id: "side", name: "邊單", ticker: "SIDE", cost: 1, type: "minion", attack: 1, health: 2, text: "雙邊報價的一邊。", rarity: "common", seat: "any", desk: "maker", art: "day", target: "none" },
  { id: "wallq", name: "賣牆", ticker: "ASK", cost: 1, type: "minion", attack: 0, health: 4, text: "護盤。", rarity: "common", seat: "any", desk: "maker", art: "bond", target: "none", taunt: true },
  { id: "wallr", name: "買牆", ticker: "BID", cost: 1, type: "minion", attack: 1, health: 4, text: "護盤。", rarity: "common", seat: "any", desk: "maker", art: "hedge", target: "none", taunt: true },
  { id: "crosser", name: "成交", ticker: "FILL", cost: 2, type: "minion", attack: 3, health: 3, text: "當沖。", rarity: "common", seat: "any", desk: "maker", art: "sq", target: "none", rush: true },
  { id: "depth", name: "水深", ticker: "DEEP", cost: 5, type: "minion", attack: 5, health: 5, text: "護盤。", rarity: "rare", seat: "any", desk: "whale", art: "sov", target: "none", taunt: true },
  { id: "gulp", name: "吞板", ticker: "GULP", cost: 4, type: "spell", text: "對所有敵方標的造成 2 點傷害。", rarity: "rare", seat: "any", desk: "whale", art: "dry", target: "none", effects: [{ k: "dmg", n: 2, to: "allEnemyMinions" }] },
  { id: "lot", name: "一口倉", ticker: "LOT", cost: 6, type: "minion", attack: 6, health: 5, text: "市價。", rarity: "epic", seat: "any", desk: "whale", art: "btc", target: "none", charge: true },
  { id: "tide", name: "潮汐", ticker: "TIDE", cost: 4, type: "minion", attack: 3, health: 5, text: "護盤。", rarity: "common", seat: "any", desk: "whale", art: "etf", target: "none", taunt: true },
  { id: "vault", name: "金庫", ticker: "VAULT", cost: 3, type: "minion", attack: 2, health: 4, text: "護盤。", rarity: "common", seat: "any", desk: "whale", art: "bond", target: "none", taunt: true },
  { id: "press", name: "壓價", ticker: "PRESS", cost: 3, type: "spell", text: "對一個敵方標的造成 3 點傷害。", rarity: "common", seat: "any", desk: "whale", art: "sq", target: "enemyMinion", effects: [{ k: "dmg", n: 3, to: "target" }] },
  { id: "bulk", name: "大宗", ticker: "BULK", cost: 7, type: "minion", attack: 7, health: 7, text: "一筆寫進盤面的大單。", rarity: "epic", seat: "any", desk: "whale", art: "nvda", target: "none" },
  { id: "wh-drain", name: "抽走流動性", ticker: "DRAIN", cost: 6, type: "spell", text: "對所有敵方標的造成 3 點傷害，並回復 4 點淨值。", rarity: "epic", seat: "house", desk: "whale", art: "sys", target: "none", effects: [{ k: "dmg", n: 3, to: "allEnemyMinions" }, { k: "heal", n: 4, to: "myHero" }] },
  { id: "wh-levi", name: "利維坦", ticker: "LEVI", cost: 8, type: "minion", attack: 8, health: 8, text: "市價。上場當回合就能攻擊。", rarity: "epic", seat: "house", desk: "whale", art: "btc", target: "none", charge: true },
  { id: "wh-lock", name: "鎖倉", ticker: "LOCK", cost: 5, type: "minion", attack: 3, health: 8, text: "護盤，止損。", rarity: "epic", seat: "house", desk: "whale", art: "fund", target: "none", taunt: true, divine: true },
  { id: "wh-wave", name: "熔斷", ticker: "HALT", cost: 5, type: "spell", text: "對所有敵方標的造成 3 點傷害。", rarity: "epic", seat: "house", desk: "whale", art: "dry", target: "none", effects: [{ k: "dmg", n: 3, to: "allEnemyMinions" }] },
  { id: "wh-pier", name: "打樁", ticker: "PIER", cost: 4, type: "spell", text: "召喚三個 1/4 護盤。", rarity: "epic", seat: "house", desk: "whale", art: "etf", target: "none", effects: [{ k: "summon", defId: "pier" }, { k: "summon", defId: "pier" }, { k: "summon", defId: "pier" }] },
  { id: "wr-gulp", name: "一口價", ticker: "ALL", cost: 7, type: "spell", text: "召喚三個 3/3 大單。", rarity: "epic", seat: "retail", desk: "whale", art: "fomo", target: "none", effects: [{ k: "summon", defId: "chunk" }, { k: "summon", defId: "chunk" }, { k: "summon", defId: "chunk" }] },
  { id: "wr-raid", name: "掃貨令", ticker: "RAID", cost: 3, type: "spell", text: "召喚兩個 2/1 市價。", rarity: "epic", seat: "retail", desk: "whale", art: "tsla", target: "none", effects: [{ k: "summon", defId: "paw" }, { k: "summon", defId: "paw" }] },
  { id: "wr-spike", name: "拉抬", ticker: "SPIKE", cost: 4, type: "spell", text: "你的所有標的獲得 +2/+2。", rarity: "epic", seat: "retail", desk: "whale", art: "qe", target: "none", effects: [{ k: "buff", a: 2, h: 2, to: "allFriendly" }] },
  { id: "wr-breach", name: "破口", ticker: "GAP", cost: 5, type: "spell", text: "對對手造成 6 點傷害。", rarity: "epic", seat: "retail", desk: "whale", art: "beat", target: "none", effects: [{ k: "dmg", n: 6, to: "enemyHero" }] },
  { id: "wr-stamp", name: "踩踏", ticker: "STOMP", cost: 6, type: "minion", attack: 5, health: 4, text: "市價，波動。每回合可以攻擊兩次。", rarity: "epic", seat: "retail", desk: "whale", art: "tsla", target: "none", charge: true, windfury: true },
  { id: "spread", name: "價差", ticker: "SPR", cost: 2, type: "minion", attack: 1, health: 3, text: "站在買賣中間的薄單。", rarity: "common", seat: "any", desk: "maker", art: "hedge", target: "none" },
  { id: "book", name: "掛簿", ticker: "BOOK", cost: 2, type: "spell", text: "召喚一個 1/2 護盤報價。", rarity: "common", seat: "any", desk: "maker", art: "report", target: "none", effects: [{ k: "summon", defId: "slip" }] },
  { id: "both", name: "雙邊", ticker: "BOTH", cost: 3, type: "spell", text: "召喚兩個 1/2 邊單。", rarity: "rare", seat: "any", desk: "maker", art: "etf", target: "none", effects: [{ k: "summon", defId: "side" }, { k: "summon", defId: "side" }] },
  { id: "tick", name: "一檔", ticker: "TICK", cost: 1, type: "minion", attack: 1, health: 2, text: "最薄的一檔。", rarity: "common", seat: "any", desk: "maker", art: "day", target: "none" },
  { id: "stock", name: "庫存", ticker: "INV", cost: 4, type: "minion", attack: 2, health: 5, text: "護盤。", rarity: "rare", seat: "any", desk: "maker", art: "bond", target: "none", taunt: true },
  { id: "mh-flip", name: "拉開價差", ticker: "WIDE", cost: 5, type: "spell", text: "你的標的獲得 +1/+3，並對所有敵方標的造成 1 點傷害。", rarity: "epic", seat: "house", desk: "maker", art: "inv", target: "none", effects: [{ k: "buff", a: 1, h: 3, to: "allFriendly" }, { k: "dmg", n: 1, to: "allEnemyMinions" }] },
  { id: "mh-pull", name: "撤深度", ticker: "PULL", cost: 4, type: "spell", text: "消滅一個動能小於或等於 5 的敵方標的。", rarity: "epic", seat: "house", desk: "maker", art: "cut", target: "enemyMinion", effects: [{ k: "destroy", maxAtk: 5 }] },
  { id: "mh-wall", name: "賣出牆", ticker: "WALL", cost: 5, type: "spell", text: "召喚三個 0/4 護盤，並抽一張牌。", rarity: "epic", seat: "house", desk: "maker", art: "qe", target: "none", effects: [{ k: "summon", defId: "wallq" }, { k: "summon", defId: "wallq" }, { k: "summon", defId: "wallq" }, { k: "draw", n: 1 }] },
  { id: "mh-fee", name: "手續費", ticker: "FEE", cost: 3, type: "spell", text: "對對手造成 2 點傷害，並抽兩張牌。", rarity: "epic", seat: "house", desk: "maker", art: "gold", target: "none", effects: [{ k: "dmg", n: 2, to: "enemyHero" }, { k: "draw", n: 2 }] },
  { id: "mh-book", name: "停牌簿", ticker: "BOOK", cost: 6, type: "spell", text: "對所有敵方標的造成 2 點傷害，並回復 4 點淨值。", rarity: "epic", seat: "house", desk: "maker", art: "halt", target: "none", effects: [{ k: "dmg", n: 2, to: "allEnemyMinions" }, { k: "heal", n: 4, to: "myHero" }] },
  { id: "mr-eat", name: "吃貨牆", ticker: "EAT", cost: 4, type: "spell", text: "召喚三個 1/4 護盤，並抽一張牌。", rarity: "epic", seat: "retail", desk: "maker", art: "hedge", target: "none", effects: [{ k: "summon", defId: "wallr" }, { k: "summon", defId: "wallr" }, { k: "summon", defId: "wallr" }, { k: "draw", n: 1 }] },
  { id: "mr-scalp", name: "剝頭皮", ticker: "SCALP", cost: 2, type: "minion", attack: 3, health: 1, text: "市價。", rarity: "epic", seat: "retail", desk: "maker", art: "day", target: "none", charge: true },
  { id: "mr-cross", name: "交叉盤", ticker: "X", cost: 5, type: "spell", text: "召喚兩個 3/3 當沖。", rarity: "epic", seat: "retail", desk: "maker", art: "sq", target: "none", effects: [{ k: "summon", defId: "crosser" }, { k: "summon", defId: "crosser" }] },
  { id: "mr-hit", name: "打到價", ticker: "HIT", cost: 4, type: "spell", text: "對一個敵方標的造成 4 點傷害，並抽一張牌。", rarity: "epic", seat: "retail", desk: "maker", art: "vix", target: "enemyMinion", effects: [{ k: "dmg", n: 4, to: "target" }, { k: "draw", n: 1 }] },
  { id: "mr-print", name: "印價", ticker: "PRINT", cost: 6, type: "spell", text: "你的所有標的獲得 +2/+2，並召喚一個 2/2。", rarity: "epic", seat: "retail", desk: "maker", art: "qe", target: "none", effects: [{ k: "buff", a: 2, h: 2, to: "allFriendly" }, { k: "summon", defId: "uw" }] },
  { id: "sprout", name: "新芽", ticker: "BUD", cost: 1, type: "minion", attack: 1, health: 2, text: "回合結束時 +1/+1。", rarity: "common", seat: "any", desk: "growth", art: "etf", target: "none", endTurn: [{ k: "buff", a: 1, h: 1, to: "target" }] },
  { id: "seed", name: "播種", ticker: "SEED", cost: 1, type: "spell", text: "召喚一個 1/2 新芽。", rarity: "common", seat: "any", desk: "growth", art: "fund", target: "none", effects: [{ k: "summon", defId: "sprout" }] },
  { id: "innerv", name: "注資", ticker: "IN", cost: 1, type: "spell", text: "獲得 2 點流動性。只在本回合。", rarity: "common", seat: "any", desk: "growth", art: "gold", target: "none", effects: [{ k: "mana", n: 2 }] },
  { id: "wild", name: "一期複利", ticker: "C1", cost: 2, type: "spell", text: "流動性上限 +1，本回合也多 1 點。", rarity: "common", seat: "any", desk: "growth", art: "qe", target: "none", effects: [{ k: "ramp", n: 1 }] },
  { id: "sap", name: "樹苗", ticker: "SAP", cost: 2, type: "minion", attack: 2, health: 2, text: "回合結束時 +1/+1。", rarity: "common", seat: "any", desk: "growth", art: "hedge", target: "none", endTurn: [{ k: "buff", a: 1, h: 1, to: "target" }] },
  { id: "tend", name: "施肥", ticker: "FEED", cost: 2, type: "spell", text: "使一個友方標的獲得 +1/+2。", rarity: "common", seat: "any", desk: "growth", art: "report", target: "friendlyMinion", effects: [{ k: "buff", a: 1, h: 2, to: "target" }] },
  { id: "grove", name: "苗圃", ticker: "GROVE", cost: 3, type: "minion", attack: 1, health: 4, text: "護盤。", rarity: "common", seat: "any", desk: "growth", art: "bond", target: "none", taunt: true },
  { id: "vine", name: "藤蔓", ticker: "VINE", cost: 2, type: "minion", attack: 2, health: 3, text: "護盤。", rarity: "common", seat: "any", desk: "growth", art: "etf", target: "none", taunt: true },
  { id: "bloom", name: "開花", ticker: "BLOOM", cost: 3, type: "spell", text: "你的所有標的獲得 +1/+1。", rarity: "rare", seat: "any", desk: "growth", art: "fomo", target: "none", effects: [{ k: "buff", a: 1, h: 1, to: "allFriendly" }] },
  { id: "rain", name: "澆水", ticker: "RAIN", cost: 3, type: "spell", text: "抽一張牌，流動性上限 +1。", rarity: "rare", seat: "any", desk: "growth", art: "sys", target: "none", effects: [{ k: "draw", n: 1 }, { k: "ramp", n: 1 }] },
  { id: "canopy", name: "林冠", ticker: "LEAF", cost: 5, type: "minion", attack: 4, health: 5, text: "回合結束時 +1/+1。", rarity: "rare", seat: "any", desk: "growth", art: "nvda", target: "none", endTurn: [{ k: "buff", a: 1, h: 1, to: "target" }] },
  { id: "nourish", name: "養倉", ticker: "NUR", cost: 5, type: "spell", text: "流動性上限 +2。", rarity: "rare", seat: "any", desk: "growth", art: "qe", target: "none", effects: [{ k: "ramp", n: 2 }] },
  { id: "oak", name: "成木", ticker: "OAK", cost: 6, type: "minion", attack: 4, health: 6, text: "護盤。", rarity: "rare", seat: "any", desk: "growth", art: "sov", target: "none", taunt: true },
  { id: "ancient", name: "古木", ticker: "OLD", cost: 8, type: "minion", attack: 8, health: 8, text: "複利養到最後的大倉。", rarity: "epic", seat: "any", desk: "growth", art: "btc", target: "none" },
  { id: "gh-force", name: "強制複利", ticker: "X2", cost: 3, type: "spell", text: "流動性上限 +2。", rarity: "epic", seat: "house", desk: "growth", art: "gold", target: "none", effects: [{ k: "ramp", n: 2 }] },
  { id: "gh-root", name: "深根", ticker: "ROOT", cost: 5, type: "minion", attack: 3, health: 7, text: "護盤。回合結束時流動性上限 +1。", rarity: "epic", seat: "house", desk: "growth", art: "fund", target: "none", taunt: true, endTurn: [{ k: "ramp", n: 1 }] },
  { id: "gh-canopy", name: "樹冠協議", ticker: "TOP", cost: 4, type: "spell", text: "你的所有標的獲得 +2/+2。", rarity: "epic", seat: "house", desk: "growth", art: "nvda", target: "none", effects: [{ k: "buff", a: 2, h: 2, to: "allFriendly" }] },
  { id: "gh-iron", name: "鐵樹", ticker: "IRON", cost: 7, type: "minion", attack: 6, health: 8, text: "護盤，止損。", rarity: "epic", seat: "house", desk: "growth", art: "sov", target: "none", taunt: true, divine: true },
  { id: "gh-yield", name: "收成", ticker: "YIELD", cost: 6, type: "spell", text: "抽三張牌，流動性上限 +1。", rarity: "epic", seat: "house", desk: "growth", art: "report", target: "none", effects: [{ k: "draw", n: 3 }, { k: "ramp", n: 1 }] },
  { id: "gr-burst", name: "爆芽", ticker: "POP", cost: 2, type: "spell", text: "召喚兩個 1/2 新芽。", rarity: "epic", seat: "retail", desk: "growth", art: "fomo", target: "none", effects: [{ k: "summon", defId: "sprout" }, { k: "summon", defId: "sprout" }] },
  { id: "gr-over", name: "過度成長", ticker: "OVER", cost: 4, type: "spell", text: "使一個友方標的獲得 +4/+4。", rarity: "epic", seat: "retail", desk: "growth", art: "tsla", target: "friendlyMinion", effects: [{ k: "buff", a: 4, h: 4, to: "target" }] },
  { id: "gr-forest", name: "成林", ticker: "WOOD", cost: 5, type: "spell", text: "召喚兩個 2/2 樹苗。", rarity: "epic", seat: "retail", desk: "growth", art: "hedge", target: "none", effects: [{ k: "summon", defId: "sap" }, { k: "summon", defId: "sap" }] },
  { id: "gr-swing", name: "抽高", ticker: "UP", cost: 4, type: "minion", attack: 4, health: 4, text: "市價。上場當回合就能攻擊。", rarity: "epic", seat: "retail", desk: "growth", art: "beat", target: "none", charge: true },
  { id: "gr-titan", name: "巨木", ticker: "TITAN", cost: 6, type: "minion", attack: 7, health: 7, text: "當沖。上場當回合可以打標的。", rarity: "epic", seat: "retail", desk: "growth", art: "btc", target: "none", rush: true },
];

export const CARDS: Record<string, CardDef> = Object.fromEntries(list.map((c) => [c.id, c]));

export const DECKS: Record<Desk, string[]> = {
  whale: [
    "meme", "meme", "etf", "etf", "day", "day", "gold",
    "beat", "beat", "eth", "sq", "lev", "tsla", "tsla", "qe", "nvda", "btc", "sov",
    "depth", "depth", "gulp", "gulp", "lot", "tide", "tide", "vault", "vault", "press", "press", "bulk",
  ],
  maker: [
    "meme", "meme", "etf", "etf", "day", "day", "gold",
    "hedge", "hedge", "halt", "halt", "bond", "bond", "inv", "cut", "dry", "pop", "fund", "report", "vix",
    "spread", "spread", "book", "book", "both", "both", "tick", "tick", "stock", "stock",
  ],
  growth: [
    "meme", "meme", "etf", "etf", "day", "day", "gold",
    "sprout", "sprout", "seed", "seed", "innerv", "innerv", "wild", "wild",
    "sap", "sap", "tend", "tend", "grove", "grove", "vine", "vine", "oak", "oak",
    "nourish", "canopy", "bloom", "ancient", "rain",
  ],
};

export const BOMBS: Record<Desk, Record<Seat, string[]>> = {
  whale: {
    house: ["wh-drain", "wh-levi", "wh-lock", "wh-wave", "wh-pier"],
    retail: ["wr-gulp", "wr-raid", "wr-spike", "wr-breach", "wr-stamp"],
  },
  maker: {
    house: ["mh-flip", "mh-pull", "mh-wall", "mh-fee", "mh-book"],
    retail: ["mr-eat", "mr-scalp", "mr-cross", "mr-hit", "mr-print"],
  },
  growth: {
    house: ["gh-force", "gh-root", "gh-canopy", "gh-iron", "gh-yield"],
    retail: ["gr-burst", "gr-over", "gr-forest", "gr-swing", "gr-titan"],
  },
};

function assertDecks() {
  if (Object.keys(CARDS).length !== list.length) throw new Error("重複的卡牌編號");
  for (const desk of ["whale", "maker", "growth"] as Desk[]) {
    if (DECKS[desk].length !== 30) throw new Error(`${desk} 基礎牌不是 30 張`);
    for (const seat of ["house", "retail"] as Seat[]) {
      if (BOMBS[desk][seat].length !== 5) throw new Error(`${desk} ${seat} 備用牌不是 5 張`);
      for (const id of BOMBS[desk][seat]) {
        const def = CARDS[id];
        if (!def) throw new Error(`備用牌不存在 ${id}`);
        if (def.seat !== seat || def.desk !== desk) throw new Error(`${id} 不是 ${desk} ${seat} 專屬`);
      }
    }
    for (const id of DECKS[desk]) {
      const def = CARDS[id];
      if (!def) throw new Error(`牌組引用不存在的牌 ${id}`);
      if (def.seat !== "any") throw new Error(`${id} 不該放進基礎牌`);
    }
  }
}

assertDecks();

export function bombList(desk: Desk, seat: Seat): CardDef[] {
  return BOMBS[desk][seat].map((id) => CARDS[id]!);
}

export function deckSummary(desk: Desk): { def: CardDef; count: number }[] {
  const map = new Map<string, number>();
  for (const id of DECKS[desk]) map.set(id, (map.get(id) ?? 0) + 1);
  return [...map.entries()]
    .map(([id, count]) => ({ def: CARDS[id]!, count }))
    .sort((a, b) => a.def.cost - b.def.cost || a.def.name.localeCompare(b.def.name, "zh-Hant"));
}
